name: Clippy
on: [ push, pull_request ]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          components: clippy
      - uses: actions/checkout@master
      - name: Clippy
        run: cargo clippy --workspace --all-features -- -Dwarnings
